name: Tests

# Test django-datorum on:
#   all supported Django and Python versions

on:
  push:
  pull_request:

jobs:
  test:
    name: py-${{ matrix.python-version }} dj-${{ matrix.django-version }} Datorum
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        django-version:
          - "3.2"
          - "4.0"
          - "4.1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: django-datorum
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "django~=${{ matrix.django-version }}.0"
      - name: Test
        working-directory: django-datorum
        run: |
          pytest
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          name: ${{ matrix.python-version }}-${{ matrix.django-version }}-postgres
